#!/usr/bin/env python3
"""Build clean answer-only SFT message mixtures.

The source answer_only task generated by prepare_data.py intentionally adds a
"Training subtask" prefix for multitask trace runs. For a paper baseline that
compares trace supervision against no-trace final-answer supervision, that
prefix is unwanted. This script strips it and builds weighted no-trace message
files with the same update budget as a selected trace run.
"""

from __future__ import annotations

import argparse
import copy
import json
import re
from collections import Counter
from pathlib import Path
from typing import Any


TASK_PREFIX_RE = re.compile(
    r"^Training subtask: produce ONLY the final grounded answer\. "
    r"Do not include a <think> block\. End with \[\[END-OF-ANSWER\]\]\.\n\n",
    flags=re.IGNORECASE,
)


def read_jsonl(path: Path):
    with path.open("r", encoding="utf-8") as f:
        for lineno, line in enumerate(f, 1):
            if not line.strip():
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"{path}:{lineno}: invalid JSON: {exc}") from exc


def strip_training_prefix(row: dict[str, Any]) -> dict[str, Any]:
    row = copy.deepcopy(row)
    for msg in row.get("messages") or []:
        if msg.get("role") != "user":
            continue
        content = str(msg.get("content") or "")
        msg["content"] = TASK_PREFIX_RE.sub("", content, count=1)
    return row


def assistant_text(row: dict[str, Any]) -> str:
    for msg in reversed(row.get("messages") or []):
        if msg.get("role") == "assistant":
            return str(msg.get("content") or "")
    return ""


def validate_answer_only(row: dict[str, Any], source: str, line_no: int) -> None:
    text = assistant_text(row)
    if not text:
        raise ValueError(f"{source}:{line_no}: missing assistant content")
    low = text.lower()
    if "<think>" in low or "</think>" in low:
        raise ValueError(f"{source}:{line_no}: answer-only assistant contains think tags")
    if "[[END-OF-ANSWER]]" not in text:
        raise ValueError(f"{source}:{line_no}: missing sentinel")
    for msg in row.get("messages") or []:
        if msg.get("role") == "user" and str(msg.get("content") or "").startswith("Training subtask:"):
            raise ValueError(f"{source}:{line_no}: training task prefix was not stripped")


def write_weighted_rows(
    out_f,
    path: Path,
    *,
    prompt_family: str,
    weight: int,
    rows_in: Counter[str],
    rows_out: Counter[str],
) -> None:
    if weight <= 0:
        return
    for line_no, row in enumerate(read_jsonl(path), 1):
        rows_in[prompt_family] += 1
        row = strip_training_prefix(row)
        validate_answer_only(row, str(path), line_no)
        for copy_idx in range(weight):
            new_row = dict(row)
            new_row["task"] = "answer_only"
            new_row["prompt_family"] = prompt_family
            if weight > 1:
                new_row["weighted_copy_idx"] = copy_idx
            out_f.write(json.dumps(new_row, ensure_ascii=False) + "\n")
            rows_out[prompt_family] += 1


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--final-only-input", type=Path, required=True)
    parser.add_argument("--minimal-input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--final-only-weight", type=int, default=8)
    parser.add_argument("--minimal-weight", type=int, default=4)
    args = parser.parse_args()

    if args.final_only_weight < 0 or args.minimal_weight < 0:
        raise SystemExit("Weights must be >= 0")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    rows_in: Counter[str] = Counter()
    rows_out: Counter[str] = Counter()
    with args.output.open("w", encoding="utf-8") as out_f:
        write_weighted_rows(
            out_f,
            args.final_only_input,
            prompt_family="answer_only_final_only",
            weight=args.final_only_weight,
            rows_in=rows_in,
            rows_out=rows_out,
        )
        write_weighted_rows(
            out_f,
            args.minimal_input,
            prompt_family="answer_only_minimal",
            weight=args.minimal_weight,
            rows_in=rows_in,
            rows_out=rows_out,
        )

    print(json.dumps({
        "final_only_input": str(args.final_only_input),
        "minimal_input": str(args.minimal_input),
        "output": str(args.output),
        "final_only_weight": args.final_only_weight,
        "minimal_weight": args.minimal_weight,
        "rows_in": dict(sorted(rows_in.items())),
        "rows_out": dict(sorted(rows_out.items())),
        "total_rows_out": sum(rows_out.values()),
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
